name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        redis-version: [6]
      
      # Не останавливаем другие тесты при ошибке
      fail-fast: false

    services:
      redis:
        image: redis:${{ matrix.redis-version }}
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          REDIS_PASSWORD: test_password

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        npm install -g jest@latest
        
    - name: Clear cache
      run: |
        npm cache clean --force
        rm -rf node_modules/.cache
        redis-cli -h localhost -p 6379 -a test_password FLUSHALL || true
        
    - name: Setup test environment
      run: |
        echo "NODE_ENV=test" >> $GITHUB_ENV
        echo "REDIS_HOST=localhost" >> $GITHUB_ENV
        echo "REDIS_PORT=6379" >> $GITHUB_ENV
        echo "REDIS_PASSWORD=test_password" >> $GITHUB_ENV
        echo "REDIS_DB=0" >> $GITHUB_ENV
        
    - name: Run tests
      run: |
        jest --detectOpenHandles --forceExit
      env:
        NODE_ENV: test
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        REDIS_PASSWORD: test_password
        REDIS_DB: 0
        
    - name: Upload coverage
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-${{ matrix.node-version }}
        path: coverage/
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.node-version }}
        path: reports/junit/ 